<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete (3)</name>
   <tag></tag>
   <elementGuidId>8cfdb555-8375-44de-98ce-ac56b85d894e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;example_wrapper&quot;)/div[@class=&quot;DTFC_ScrollWrapper&quot;]/div[@class=&quot;DTFC_LeftWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyLiner&quot;]/table[@class=&quot;display table table-striped table-bordered dataTable no-footer DTFC_Cloned&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/a[@class=&quot;display-mode50c42446-f968-4d5e-9cf2-085746c37e05  btn btn-default btn-sm disableButton&quot;][count(. | //a[@class = 'display-mode50c42446-f968-4d5e-9cf2-085746c37e05  btn btn-default btn-sm disableButton' and @data-toggle = 'modal' and @data-target = '#RemoveUser' and @onclick = concat('Delete(' , &quot;'&quot; , '50c42446-f968-4d5e-9cf2-085746c37e05' , &quot;'&quot; , ')') and (text() = ' Delete' or . = ' Delete')]) = count(//a[@class = 'display-mode50c42446-f968-4d5e-9cf2-085746c37e05  btn btn-default btn-sm disableButton' and @data-toggle = 'modal' and @data-target = '#RemoveUser' and @onclick = concat('Delete(' , &quot;'&quot; , '50c42446-f968-4d5e-9cf2-085746c37e05' , &quot;'&quot; , ')') and (text() = ' Delete' or . = ' Delete')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-mode50c42446-f968-4d5e-9cf2-085746c37e05  btn btn-default btn-sm disableButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#RemoveUser</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Delete('50c42446-f968-4d5e-9cf2-085746c37e05')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example_wrapper&quot;)/div[@class=&quot;DTFC_ScrollWrapper&quot;]/div[@class=&quot;DTFC_LeftWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyLiner&quot;]/table[@class=&quot;display table table-striped table-bordered dataTable no-footer DTFC_Cloned&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/a[@class=&quot;display-mode50c42446-f968-4d5e-9cf2-085746c37e05  btn btn-default btn-sm disableButton&quot;]</value>
   </webElementProperties>
</WebElementEntity>
