<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select001-BASIC</name>
   <tag></tag>
   <elementGuidId>fb2032aa-22c9-4e76-9845-ef11297e3d28</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SalarySacrificeAllowance0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select001-BASIC PAY002-BASICHRS019-Guaranteed Pay070-Statutory Maternity Pay071-Statutory Sick Pay072-Statutory Paretal Pay073-Statutory Adoption Pay074-Statutory Pay Adoption075-Shared Parental Pay Birth076-SharedParentalPayAdoption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SalarySacrificeAllowance0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
