<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectAnnual Dif</name>
   <tag></tag>
   <elementGuidId>e3c11423-ec7d-4287-8e1e-e163ad55deed</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EarningsStart0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectAnnual DifferenceAnnual LELAnnual Pension Reform DifferenceAnnual Pension Lower ThresholdAnnual Pension Upper ThresholdAnnual UAPAnnual UELFortnightly DifferenceFortnightly LELFortnightly Pension Reform DifferenceFortnightly Pension Lower ThresholdFortnightly Pension Upper ThresholdFortnightly UAPFortnightly UELLunar DifferenceLunar LELLunar Pension Reform DifferenceLunar Pension Lower ThresholdLunar Pension Upper ThresholdLunar UAPLunar UELMonthly DifferenceMonthly LELMonthly Pension Reform DifferenceMonthly Pension Lower ThresholdMonthly Pension Upper ThresholdMonthly UAPMonthly UELWeekly DifferenceWeekly LELWeekly Pension Reform DifferenceWeekly Pension Lower ThresholdWeekly Pension Upper ThresholdWeekly UAPWeekly UEL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EarningsStart0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
