<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectNon-tax Ap</name>
   <tag></tag>
   <elementGuidId>f38a13c4-b36b-47b2-bee8-6f530df86798</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Typeofscheme0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectNon-tax Approved Comp Scheme - No Tax Rel, C/o = MNon-tax Approved Sal Related Sch - No Tax Rel, C/o = YNon-tax Approved Not C/o - No Tax RelOtherPers Pen (inc SPPP &amp; Stakeh) - No Tax RelTax Approved Comp Sch - Tax Relief. C/o = MTax Approved Salary Related  - Tax Relief. C/o = YTax Approved not C/o - Tax Relief</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Typeofscheme0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
