<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectR002R009R0</name>
   <tag></tag>
   <elementGuidId>42e55ac7-2f53-403b-aba9-15d54f557020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;LinkedCompanyRate0&quot;)[count(. | //select[@id = 'LinkedCompanyRate0' and @class = 'form-control' and (text() = 'Please selectR002R009R003' or . = 'Please selectR002R009R003')]) = count(//select[@id = 'LinkedCompanyRate0' and @class = 'form-control' and (text() = 'Please selectR002R009R003' or . = 'Please selectR002R009R003')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkedCompanyRate0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectR002R009R003</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkedCompanyRate0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
