<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select111112-SDW</name>
   <tag></tag>
   <elementGuidId>8230a8d9-aa37-42c3-897c-b9f3772ba249</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OrgName0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select111112-SDWorx-Ouma123456-Sdworx-Ouma2111113-SDWorx-Sanjeev311116-TestAuto6111111-SDWorx-Nadia311112-TestAuto1256315-SDWorx-QA311117-TestAuto7311111-TestAuto125896-SDWorx-Test111115-SDWorx-Prasan311114-311114311115-311115311113-TestAuto2100000-SDWorx-Nischala888888-Nadia Test111116-SDWorx-Dev111118-SDWorx-Steve</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrgName0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
